FROM ubuntu:latest

# Propietario 
LABEL maintainer="Madelem Chico Velasco <madelenchicovelasco@gmail.com>"

# Configura el entorno
ENV DEBIAN_FRONTEND=noninteractive

# Actualiza los paquetes y instala dependencias esenciales
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    unzip \
    git \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release

# Instala Docker
RUN apt-get install -y docker.io

# Instala Git
RUN apt-get install -y git

# Instala Java (OpenJDK 11)
RUN apt-get install -y openjdk-11-jdk

# Instala Node.js
RUN apt-get install -y nodejs

# Instala .NET SDK
#RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
#    dpkg -i packages-microsoft-prod.deb && \
#    apt-get update && \
#    apt-get install -y dotnet-sdk-6.0
RUN curl -Lo dotnet.tar.gz https://download.visualstudio.microsoft.com/download/pr/911f82cf-0f87-46c2-8d70-44fab9a0f3c9/137ec23686722b8119bd62def8d7b117/dotnet-sdk-9.0.100-preview.2.24157.14-linux-x64.tar.gz && \
    mkdir dotnet && \
    tar -C dotnet -xf dotnet.tar.gz && \
    rm dotnet.tar.gz && \
    export DOTNET_ROOT=~/dotnet && \
    export PATH=$PATH:~/dotnet && \
    dotnet --version

# Instala kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Instala Azure DevOps agent
RUN mkdir /azp
WORKDIR /azp
RUN curl -o azagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.193.0/vsts-agent-linux-x64-2.193.0.tar.gz && \
    tar zxvf azagent.tar.gz && \
    ./bin/installdependencies.sh

COPY ./start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]