version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - '9000:9000'
    networks:
      - sonarnet
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    networks:
      - sonarnet

networks:
  sonarnet: